export const SING_IN = '/singin'
export const HOME = '/'
export const DOCTAR = '/doctar'
export const CONTACT = '/contact'
export const APPOINTMENT = '/appointment'
export const ADMIN = '/adminpanel'
export const ALBUM = '/album'
export const FAQ ='/faq'